### ISSUE TITLE
[Controller] Mock Controller

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#5]
# 1. TODO
- [x] FAQController
- [x] MemberController
- [x] ConcertController
- [x] DonateController
- [x] #17
- [x] ApplyController
---
# 2. Test Case
- [x] MockMvc 이용하여 올바른 결과값이 나오는지 test.
- [x] FAQControllerTest
- [x] MemberControllerTest
- [x] ConcertControllerTest
- [x] DonateControllerTest
- [x] PaymentControllerTest
- [x] ApplyControllerTest
---
# 3. 유의사항
- Mock Controller 클래스를 따로 작성하지 않고 각 Controller의 endpoint마다 원하는 형태의 데이터를 하드코딩하여 반환하도록 한다.
- Notion의 API 명세서를 참고하여 작성한다.

**Comment by AllyHyeseongKim** [comment]
LGTM
